//
// Created by david on 10.3.16.
//

#ifndef IPK_PROJ1_HELPERS_H
#define IPK_PROJ1_HELPERS_H

#include <iostream>
#include <stdlib.h>

enum ret_val {
	EOK,
	WRONG_ARGUMENTS,
	URL_PARSE_ERROR,
	SOCKET_ERROR,
	GET_HOST_BY_NAME_ERROR,
	CONNECT_ERROR,
	SEND_ERROR,
	RECV_ERROR,
	CLOSE_ERROR,
	REDIRECTION_EXCEEDED_ERROR,
	FILE_NOT_OPENED,
	UNIMPLEMENTED_HTTP_RET_VAL,
	INTERNAL_ERROR
};

#endif //IPK_PROJ1_HELPERS_H
